#!/bin/bash
# Copyright (2018): Jonas Rylund Glesaaen (jonas@glesaaen.com)
# License: MIT
#
# Utility script that generates machinefiles used by MPI if one needs to do a
# multi-MPI run on clusters with scattering schedulers.
#
# Usage: machinefiles [--help] [--check] [--fills] [--dry] [--no_overwrite]"
#                  [--pattern PATTERN] [--total_nodes NODES]"
#                  <--cores_per_run CORES> <--cores_per_node CORES>"
#                  <--runs RUNS> <--file NODEFILE>"
#
# For a more detailed description of the options please call
# machinefiles --help

# Program variables
# {{{

# Variables from cmd-line
Machinefiles_machinefiles=""
Machinefiles_cores_per_node=""
Machinefiles_cores_per_run=""
Machinefiles_num_nodes=""
Machinefiles_num_runs=""
Machinefiles_pattern=""

# Flags from cmd-line
Machinefiles_help_flag=""
Machinefiles_check_flag=""
Machinefiles_fill_flag=""
Machinefiles_dry_run=""
Machinefiles_overwrite=""

# }}}

# Program functions
# {{{

## Information functions
## {{{

# Print the usage string
print-usage-message ()
{
  echo "Usage: machinefiles [--help] [--check] [--fills] [--dry] [--no_overwrite]"
  echo "                 [--pattern PATTERN] [--total_nodes NODES]"
  echo "                 <--cores_per_run CORES> <--cores_per_node CORES>"
  echo "                 <--runs RUNS> <--file NODEFILE>"
}

# Print the full help message
print-help-message ()
{
  print-usage-message

  echo ""
  echo "Program parameters:"
  echo "--cores_per_run,-c CORES  Set the number of cores each run will use"
  echo "--cores_per_node,C CORES  Specify the number of cores available on each node"
  echo "--runs,-n RUNS            Set the total number of mpiruns to make machinefiles for"
  echo "--file,-f NODEFILE        Path to file containing allocated nodes"
  echo ""
  echo "Optional parameters:"
  echo "--total_nodes,-N NODES  Override the node count from the machinefiles"
  echo "--pattern PATTERN       Specify the pattern to use for the individual machinefiles"
  echo "                        These will be parsed by printf given the run-id as a paramter"
  echo "                        Default: machinefile_%d"
  echo "--help                  Print this help message"
  echo "--check                 Exit if the total core count exceeds the allocated one"
  echo "--fills                 Exit if the total core count is not exactly the allocated one"
  echo "--dry                   Print some information about the request and exit"
  echo "--no_overwrite          Check that no files will be overwritten, exit if they will"
}

## }}}

## Core count arithmatic
## {{{

# Looks up the total number of available nodes
available-nodes ()
{
  if test "x${Machinefiles_num_nodes}" == "x"; then
    RESULT=$(cat ${Machinefiles_machinefiles} | wc -l)
  else
    RESULT=${Machinefiles_num_nodes}
  fi
}

# Reduce the fraction "leftover / cores_per_node" so that we can find out how
# many batches we need and how many nodes per batch
leftover-fraction ()
{
  local leftover_cores=$((Machinefiles_cores_per_run % Machinefiles_cores_per_node))

  local fraction_expr="Fraction(${leftover_cores}, ${Machinefiles_cores_per_node})"
  local py="from fractions import Fraction; print ${fraction_expr}"

  RESULT=$(python -c "${py}")

  if [[ ! ${RESULT} = *"/"* ]]; then
    RESULT="${RESULT}/1"
  fi
}

# Gives the number of leftover "batches" or runs that will share a partially
# filled node
leftover-batch-count ()
{
  leftover-fraction
  RESULT=$(echo "${RESULT}" | cut -d '/' -f 2)
}

# Gives the number of leftover nodes used for the shared batches
leftover-node-count ()
{
  leftover-fraction
  RESULT=$(echo "${RESULT}" | cut -d '/' -f 1)
}

## }}}

## Checks
## {{{

# Checks that the allocation fits on the requested number of nodes
check-fits ()
{
  available-nodes
  local total_nodes="${RESULT}"
  local allocated_cores=$((total_nodes * Machinefiles_cores_per_node))

  if [ $((Machinefiles_cores_per_run * Machinefiles_num_runs)) -gt ${allocated_cores} ]
  then
    RESULT=0
  else
    RESULT=1
  fi
}

# Check that one fills up the entire allocation
check-fills ()
{
  available-nodes
  local total_nodes="${RESULT}"
  local allocated_cores=$((total_nodes * Machinefiles_cores_per_node))

  if [ ! $((Machinefiles_cores_per_run * Machinefiles_num_runs)) -eq ${allocated_cores} ]
  then
    RESULT=0
  else
    RESULT=1
  fi
}

check-overwrite ()
{
  for idx in $(seq 1 ${Machinefiles_num_runs})
  do
    filename=$(printf ${Machinefiles_pattern} ${idx})
    
    if [ -f ${filename} ]; then
      RESULT=1
      return 0
    fi
  done

  RESULT=0
}

## }}}

## Nodefile builds
## {{{

add-full-nodes ()
{
  local start="${1}"
  local filename="${2}"

  local full_nodes=$((Machinefiles_cores_per_run / Machinefiles_cores_per_node))

  RESULT=${start}

  if [ ! ${full_nodes} -gt 0 ]; then
    return 0
  fi

  sed -n "${start},$((start + full_nodes - 1))p" ${Machinefiles_machinefiles} | \
    sed -e "s,$,:${Machinefiles_cores_per_node}," >> \
    ${filename}

  RESULT=$((start + full_nodes))
}

add-partial-nodes ()
{
  local idx="${1}"
  local start="${2}"
  local filename="${3}"

  leftover-batch-count
  local runs_per_batch="${RESULT}"

  leftover-node-count
  local nodes_per_batch="${RESULT}"

  RESULT=${start}

  # Append the shared nodes if any
  if [ ${nodes_per_batch} -gt 0 ]
  then

    local full_nodes=$((Machinefiles_cores_per_run / Machinefiles_cores_per_node))
    local leftover_cores=$((Machinefiles_cores_per_run % Machinefiles_cores_per_node))

    local lidx=$((idx % runs_per_batch))
    local shared_offset=$(((runs_per_batch - lidx) % runs_per_batch))
    local lstart=$((start + full_nodes * shared_offset))

    sed -n "${lstart},$((lstart + nodes_per_batch - 1))p" ${Machinefiles_machinefiles} | \
      sed -e "s,$,:$((leftover_cores / nodes_per_batch))," >> \
      ${filename}

    # Increment the current line if last run in batch
    if [ $((idx % runs_per_batch)) -eq 0 ]
    then
      RESULT=$((start + nodes_per_batch))
    fi
  fi
}

build-machinefiles ()
{
  local machinefiles_line=1

  for idx in $(seq 1 ${Machinefiles_num_runs})
  do
    filename=$(printf ${Machinefiles_pattern} ${idx})
    rm -f ${filename}

    add-full-nodes ${machinefiles_line} ${filename}
    machinefiles_line="${RESULT}"

    add-partial-nodes ${idx} ${machinefiles_line} ${filename}
    machinefiles_line="${RESULT}"
  done
}

## }}}

## Information
## {{{

print-run-information ()
{
  local total_cores=$((Machinefiles_cores_per_run * Machinefiles_num_runs))

  available-nodes
  local total_nodes="${RESULT}"
  local allocated_cores=$((total_nodes * Machinefiles_cores_per_node))

  local full_nodes=$((Machinefiles_cores_per_run / Machinefiles_cores_per_node))

  leftover-batch-count
  local runs_per_batch="${RESULT}"

  leftover-node-count
  local nodes_per_batch="${RESULT}"

  local leftover_cores=$((Machinefiles_cores_per_run % Machinefiles_cores_per_node))
  local leftover_nodes=$((Machinefiles_num_runs / runs_per_batch))

  echo "Used cores: ${total_cores} / ${allocated_cores}"
  echo "Number of full nodes: ${full_nodes}"
  echo "Leftover cores per run: ${leftover_cores} / ${Machinefiles_cores_per_run}"
  echo "Leftover nodes: ${leftover_nodes} / ${total_nodes}"
  echo "Runs per leftover node: ${runs_per_batch}"
  echo "Nodes per leftover node: ${nodes_per_batch}"
}

## }}}

# }}}

# Main run
# {{{

## Parse program options
## {{{

parse-program-options ()
{
  getopt_results=$(\
    getopt \
      -s bash \
      -o f:c:C:n:N:h \
      --long file:,cores_per_run:,cores_per_node:,runs:total_nodes:,pattern:,help,check,fills,dry,no_overwrite \
      -- "$@")

  if test $? != 0
  then
    print-usage-message
    exit 1
  fi

  eval set -- "${getopt_results}"

  while true
  do
    case "$1" in
      --help|-h)
        Machinefiles_help_flag=1;
        shift 1;
        ;;
      --file|-f)
        Machinefiles_machinefiles="$2";
        shift 2;
        ;;
      --cores_per_run|-c)
        Machinefiles_cores_per_run="$2";
        shift 2;
        ;;
      --cores_per_node|-C)
        Machinefiles_cores_per_node="$2";
        shift 2;
        ;;
      --runs|-n)
        Machinefiles_num_runs="$2"
        shift 2;
        ;;
      --total_nodes|-N)
        Machinefiles_num_nodes="$2"
        shift 2;
        ;;
      --pattern)
        Machinefiles_pattern="$2"
        shift 2;
        ;;
      --check)
        Machinefiles_check_flag="1"
        shift 1;
        ;;
      --fills)
        Machinefiles_check_flag="1"
        Machinefiles_fill_flag="1"
        shift 1;
        ;;
      --dry)
        Machinefiles_dry_run="1"
        shift 1;
        ;;
      --no_overwrite)
        Machinefiles_overwrite="1"
        shift 1;
        ;;
      --)
        shift
        break
        ;;
      *)
        echo "$0: Unparseable option $1"
        exit 1
        ;;
    esac
  done
}

## }}}

parse-program-options "$@"

if test "${Machinefiles_help_flag}" == "1"; then
  print-help-message
  exit 0
fi

## Pre possible dry run parameter checks
## {{{

if test "x${Machinefiles_cores_per_node}" == "x"
then
  echo "--cores_per_node not set"
  print-usage-message
  exit 1
fi

if test "x${Machinefiles_cores_per_run}" == "x"
then
  echo "--cores_per_run not set"
  print-usage-message
  exit 1
fi

if test "x${Machinefiles_num_runs}" == "x"
then
  echo "--runs not set"
  print-usage-message
  exit 1
fi

## }}}

## Setting defaults
## {{{

if test "x${Machinefiles_pattern}" == "x"
then
  Machinefiles_pattern="machinefile_%d"
fi

## }}}
 
## Preliminary checks and dry runs
## {{{

if test "${Machinefiles_check_flag}" == "1"; then
  check-fits

  if test "${RESULT}" == "0"; then
    echo "The job does not fit within the requested core count"
    exit 1
  fi
fi

if test "${Machinefiles_fill_flag}" == "1"; then
  check-fills

  if test "${RESULT}" == "0"; then
    echo "The job does not fill the requested core count"
    exit 1
  fi
fi

if test "${Machinefiles_overwrite}" == "1"; then
  check-overwrite

  if test "${RESULT}" == "1"; then
    echo "The program overwrites files"
    exit 1
  fi
fi

if test "${Machinefiles_dry_run}" == "1"; then
  print-run-information
  exit 0
fi

## }}}

## Pre possible dry run parameter checks
## {{{

if test "x${Machinefiles_machinefiles}" == "x"
then
  echo "--file not set"
  print-usage-message
  exit 1
fi

if [ ! -f ${Machinefiles_machinefiles} ];
then
  echo "The machinefile \"${Machinefiles_machinefiles}\" is not a regular file"
  exit 1
fi

## }}}

build-machinefiles

# }}}
